# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsblog', '0002_posths'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.TextField(default='Da'),
        ),
    ]
